const C = require('./constants');

module.exports.templates = {
    'bunker1': {
        description: 'Level 1 bunker-style Stronghold',
        rewardLevel: 1,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 1, strongholdBehavior: 'bunker1' },
            { type: C.STRUCTURE_ROAD,         dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,         dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,      dx:  0, dy:  0 },
            { type: C.STRUCTURE_RAMPART,      dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,      dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,        dx:  1, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,    dx:  1, dy:  0 },
        ]
    },
    'bunker2': {
        description: 'Level 2 bunker-style Stronghold',
        rewardLevel: 2,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 2, strongholdBehavior: 'bunker2' },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,  dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy: -1 },
            { type: C.STRUCTURE_CONTAINER,  dx: -1, dy:  0 },
        ]
    },
    'bunker3': {
        description: 'Level 3 bunker-style Stronghold',
        rewardLevel: 3,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 3, strongholdBehavior: 'bunker3' },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,  dx:  1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy: -1 },
            { type: C.STRUCTURE_CONTAINER,  dx: -2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  2 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,  dx:  0, dy:  2 },
        ]
    },
    'bunker4': {
        description: 'Level 4 bunker-style Stronghold',
        rewardLevel: 4,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 4, strongholdBehavior: 'bunker4' },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,  dx:  2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy: -1 },
            { type: C.STRUCTURE_CONTAINER,  dx: -2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  2 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,  dx:  0, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -2 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy: -1 },
            { type: C.STRUCTURE_CONTAINER,  dx:  0, dy: -2 },
        ]
    },
    'bunker5': {
        description: 'Level 5 bunker-style Stronghold',
        rewardLevel: 5,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 5, strongholdBehavior: 'bunker5' },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  3 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  3 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  3 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  3 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,  dx:  2, dy:  2 },
            { type: C.STRUCTURE_CONTAINER,  dx: -2, dy: -2 },
            { type: C.STRUCTURE_CONTAINER,  dx:  2, dy: -2 },
            { type: C.STRUCTURE_CONTAINER,  dx: -2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  2 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -2 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  3 },
            { type: C.STRUCTURE_TOWER,      dx:  0, dy: -2 },
            { type: C.STRUCTURE_TOWER,      dx:  0, dy:  2 },
        ]
    }
};

module.exports.coreRewards = {
    [C.RESOURCE_SILICON]: [C.RESOURCE_SILICON, C.RESOURCE_WIRE, C.RESOURCE_SWITCH, C.RESOURCE_TRANSISTOR, C.RESOURCE_MICROCHIP, C.RESOURCE_CIRCUIT],
    [C.RESOURCE_METAL]: [C.RESOURCE_METAL, C.RESOURCE_ALLOY, C.RESOURCE_TUBE, C.RESOURCE_FIXTURES, C.RESOURCE_FRAME, C.RESOURCE_HYDRAULICS],
    [C.RESOURCE_BIOMASS]: [C.RESOURCE_BIOMASS, C.RESOURCE_CELL, C.RESOURCE_PHLEGM, C.RESOURCE_TISSUE, C.RESOURCE_MUSCLE, C.RESOURCE_ORGANOID],
    [C.RESOURCE_MIST]: [C.RESOURCE_MIST, C.RESOURCE_CONDENSATE, C.RESOURCE_CONCENTRATE, C.RESOURCE_EXTRACT, C.RESOURCE_SPIRIT, C.RESOURCE_EMANATION]
};

module.exports.containerRewards = [
    C.RESOURCE_UTRIUM_BAR,
    C.RESOURCE_LEMERGIUM_BAR,
    C.RESOURCE_ZYNTHIUM_BAR,
    C.RESOURCE_KEANIUM_BAR,
    C.RESOURCE_OXIDANT,
    C.RESOURCE_REDUCTANT,
    C.RESOURCE_PURIFIER,
    C.RESOURCE_GHODIUM_MELT,
    C.RESOURCE_POWER,
    C.RESOURCE_BATTERY,
    C.RESOURCE_COMPOSITE,
    C.RESOURCE_CRYSTAL,
    C.RESOURCE_LIQUID
];
