const C = require('./constants');

module.exports.templates = {
    'bunker1': {
        description: 'Level 1 bunker-style Stronghold',
        rewardLevel: 1,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 1, strongholdBehavior: 'bunker1' },
            { type: C.STRUCTURE_RAMPART,      dx:  0, dy:  0 },
            { type: C.STRUCTURE_RAMPART,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,        dx:  1, dy:  1 },
            { type: C.STRUCTURE_ROAD,         dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,      dx:  0, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,         dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,      dx:  1, dy:  0 },
        ]
    },
    'bunker2': {
        description: 'Level 2 bunker-style Stronghold',
        rewardLevel: 2,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 2, strongholdBehavior: 'bunker2' },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  0 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  1 },
            { type: C.STRUCTURE_CONTAINER,  dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_CONTAINER,  dx: -1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  0 },
        ]
    },
    'bunker3': {
        description: 'Level 3 bunker-style Stronghold',
        rewardLevel: 3,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 3, strongholdBehavior: 'bunker3' },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  0 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  2 },
            { type: C.STRUCTURE_CONTAINER,  dx:  1, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -1 },
            { type: C.STRUCTURE_CONTAINER,  dx: -2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  0 },
            { type: C.STRUCTURE_CONTAINER,  dx:  0, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  2 },
        ]
    },
    'bunker4': {
        description: 'Level 4 bunker-style Stronghold',
        rewardLevel: 4,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 4, strongholdBehavior: 'bunker4' },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  0 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  2 },
            { type: C.STRUCTURE_CONTAINER,  dx:  2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  0 },
            { type: C.STRUCTURE_CONTAINER,  dx: -2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  0 },
            { type: C.STRUCTURE_CONTAINER,  dx:  0, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  2 },
            { type: C.STRUCTURE_CONTAINER,  dx:  0, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -2 },
        ]
    },
    'bunker5': {
        description: 'Level 5 bunker-style Stronghold',
        rewardLevel: 5,
        structures: [
            { type: C.STRUCTURE_INVADER_CORE, dx:  0, dy:  0, level: 5, strongholdBehavior: 'bunker5' },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  0 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -1 },
            { type: C.STRUCTURE_TOWER,      dx: -1, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  1 },
            { type: C.STRUCTURE_TOWER,      dx:  1, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -1 },
            { type: C.STRUCTURE_TOWER,      dx:  0, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -2 },
            { type: C.STRUCTURE_TOWER,      dx:  0, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -3 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -3 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy: -1 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy: -1 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy:  0 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy:  0 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy:  1 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy:  1 },
            { type: C.STRUCTURE_ROAD,       dx: -3, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -3, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  3, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  3, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  3 },
            { type: C.STRUCTURE_ROAD,       dx: -1, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx: -1, dy:  3 },
            { type: C.STRUCTURE_ROAD,       dx:  0, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx:  0, dy:  3 },
            { type: C.STRUCTURE_ROAD,       dx:  1, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx:  1, dy:  3 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  3 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  3 },
            { type: C.STRUCTURE_CONTAINER,  dx:  2, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy:  2 },
            { type: C.STRUCTURE_CONTAINER,  dx: -2, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy: -2 },
            { type: C.STRUCTURE_CONTAINER,  dx:  2, dy: -2 },
            { type: C.STRUCTURE_ROAD,       dx:  2, dy: -2 },
            { type: C.STRUCTURE_RAMPART,    dx:  2, dy: -2 },
            { type: C.STRUCTURE_CONTAINER,  dx: -2, dy:  2 },
            { type: C.STRUCTURE_ROAD,       dx: -2, dy:  2 },
            { type: C.STRUCTURE_RAMPART,    dx: -2, dy:  2 },
        ]
    }
};

module.exports.coreRewards = {
    [C.RESOURCE_SILICON]: [C.RESOURCE_WIRE, C.RESOURCE_SWITCH, C.RESOURCE_TRANSISTOR, C.RESOURCE_MICROCHIP, C.RESOURCE_CIRCUIT, C.RESOURCE_DEVICE],
    [C.RESOURCE_METAL]: [C.RESOURCE_ALLOY, C.RESOURCE_TUBE, C.RESOURCE_FIXTURES, C.RESOURCE_FRAME, C.RESOURCE_HYDRAULICS, C.RESOURCE_MACHINE],
    [C.RESOURCE_BIOMASS]: [C.RESOURCE_CELL, C.RESOURCE_PHLEGM, C.RESOURCE_TISSUE, C.RESOURCE_MUSCLE, C.RESOURCE_ORGANOID, C.RESOURCE_ORGANISM],
    [C.RESOURCE_MIST]: [C.RESOURCE_CONDENSATE, C.RESOURCE_CONCENTRATE, C.RESOURCE_EXTRACT, C.RESOURCE_SPIRIT, C.RESOURCE_EMANATION, C.RESOURCE_ESSENCE]
};
module.exports.coreAmounts = [0, 1000, 16000, 60000, 400000, 3000000];
module.exports.coreDensities = [10, 220, 1400, 5100, 14000, 31500];

module.exports.containerRewards = {
    [C.RESOURCE_UTRIUM_BAR]: 5,
    [C.RESOURCE_LEMERGIUM_BAR]: 5,
    [C.RESOURCE_ZYNTHIUM_BAR]: 5,
    [C.RESOURCE_KEANIUM_BAR]: 5,
    [C.RESOURCE_OXIDANT]: 5,
    [C.RESOURCE_REDUCTANT]: 5,
    [C.RESOURCE_PURIFIER]: 5,
    [C.RESOURCE_GHODIUM_MELT]: 20,
    [C.RESOURCE_BATTERY]: 10,
    [C.RESOURCE_COMPOSITE]: 10,
    [C.RESOURCE_CRYSTAL]: 15,
    [C.RESOURCE_LIQUID]: 30
};
module.exports.containerAmounts = [0, 500, 4000, 10000, 50000, 360000];

